name: Integration CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install pylint
        run: python -m pip install pylint

      - name: Run pylint
        run: pylint *.py --disable=C0114,C0116,C0304,W0611

  discord:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout
       uses: actions/checkout@v5

     - name: Send Discord message
       run: |
         curl -H "Content-Type: application/json" \
         -d "{\"content\": \"✅ CI aprovado para o commit ${{ github.sha }} na branch ${{ github.ref_name }}\"}"\
         ${{ secrets.DISCORD_WEBHOOK }}
        



 
     

     
